#!/bin/bash
# Script per testare l'applicazione localmente

echo "======================================"
echo "🎓 ITIS Orientation Coach - TEST"
echo "======================================"
echo ""
echo "✅ Streamlit è in esecuzione!"
echo ""
echo "📍 URL: http://localhost:8501"
echo ""
echo "Per accedere:"
echo "  1. Apri il browser"
echo "  2. Vai su: http://localhost:8501"
echo ""
echo "Cosa vedrai:"
echo "  - Schermata di Onboarding"
echo "  - Scegli un nickname"
echo "  - Inizia le sessioni di orientamento"
echo ""
echo "Note:"
echo "  - L'app usa LLM simulato (MockProvider)"
echo "  - Per LLM reale serve API key in .env"
echo ""
echo "Per fermare il server:"
echo "  pkill -f streamlit"
echo ""
