"""
Chat View - Interfaccia conversazione
"""

import streamlit as st
import asyncio
from datetime import datetime

from services.session_manager import SessionManager
from services.todo_manager import TodoManager


def render_chat(session_manager: SessionManager, todo_manager: TodoManager, student_id: str):
    """Render chat interface"""

    st.title("💬 Conversazione")

    # Check if there's an active session
    if "current_session_id" not in st.session_state or not st.session_state.current_session_id:
        # No active session - show start button
        last_session = session_manager.get_last_session(student_id)

        if last_session and last_session.ended_at:
            with st.expander("📋 Ultima volta abbiamo parlato di..."):
                if last_session.insights:
                    for insight in last_session.insights:
                        st.write(f"- {insight}")
                else:
                    st.write("Continuiamo da dove ci eravamo lasciati!")

        st.info("👋 Pronto per una nuova sessione?")

        if st.button("🚀 Inizia Nuova Sessione", type="primary", use_container_width=True):
            # Create new session
            session = session_manager.create_session(student_id)
            st.session_state.current_session_id = session.id

            # Add welcome message
            welcome_msg = get_welcome_message(session.role.value)
            session_manager.add_message(session.id, "assistant", welcome_msg)

            st.rerun()

    else:
        # Active session exists
        session_id = st.session_state.current_session_id
        session = session_manager.get_session(session_id)

        if not session:
            st.error("Sessione non trovata")
            st.session_state.current_session_id = None
            st.rerun()
            return

        # Session header
        col1, col2, col3 = st.columns([3, 1, 1])

        with col1:
            role_name = session.role.value.replace("_", " ").title()
            st.caption(f"🎭 Modalità: **{role_name}**")

        with col2:
            duration = (datetime.now() - session.started_at).seconds // 60
            st.caption(f"⏱️ {duration} min")

        with col3:
            if st.button("🏁 Termina", type="secondary"):
                # End session
                insights = ["Sessione completata"]  # Could be generated by LLM
                session_manager.end_session(session_id, insights)
                st.session_state.current_session_id = None
                st.success("Sessione terminata! Ottimo lavoro 💪")
                st.rerun()

        st.divider()

        # Messages container
        messages = session_manager.get_messages(session_id)

        # Display messages
        for msg in messages:
            with st.chat_message(msg.role.value):
                st.write(msg.content)

        # User input
        user_input = st.chat_input("Scrivi qui il tuo messaggio...")

        if user_input:
            # Display user message immediately
            with st.chat_message("user"):
                st.write(user_input)

            # Get LLM response
            with st.chat_message("assistant"):
                with st.spinner("Sto pensando..."):
                    try:
                        response = asyncio.run(
                            session_manager.get_llm_response(session_id, user_input)
                        )
                        st.write(response)
                    except Exception as e:
                        st.error(f"Errore: {str(e)}")

            # Check if session should close
            if session_manager.should_close_session(session_id):
                st.info("💡 Abbiamo parlato per un po'! Vuoi terminare la sessione?")

            st.rerun()


def get_welcome_message(role: str) -> str:
    """Get welcome message based on role"""
    messages = {
        "esploratore_curioso": "Ciao! 👋 Sono qui per aiutarti a scoprire cosa ti appassiona davvero. Non c'è fretta e non ci sono risposte giuste o sbagliate. Raccontami: c'è stato un progetto o un'attività che hai fatto a scuola che ti ha proprio preso?",

        "analista_empatico": "Bentornato! 🌟 Abbiamo già iniziato a scoprire alcuni tuoi interessi. Oggi vorrei approfondire un po' di più. Cosa rende una giornata 'bella' per te?",

        "mentore_pragmatico": "Ciao! 👔 Basandomi su quello che abbiamo scoperto finora, oggi possiamo iniziare a parlare di percorsi concreti. Non ti sto vendendo niente, solo esplorando opzioni insieme. Sei pronto?",

        "coach_operativo": "Hey! 💪 È il momento di passare all'azione! Vediamo insieme come realizzare i tuoi piani. Hai già qualche idea di cosa vorresti fare per primo?",

        "filosofo_riflessivo": "Ciao 🧘 Vedo che magari hai qualche dubbio o confusione, ed è completamente normale. Prenditi il tempo che serve. Di cosa vuoi parlare?"
    }

    return messages.get(role, "Ciao! Come posso aiutarti oggi?")
